version: '3.5'

services:
  mc:
    image: itzg/minecraft-server
    environment:
      EULA: "TRUE"
      ONLINE_MODE: "FALSE"
  bungeecord:
    image: itzg/bungeecord
    environment:
      BUNGEE_JAR_REVISION: "1"
      CFG_MOTD: Powered by Docker
    ports:
      - "25565:25577"
    volumes:
      - ./config.yml:/config/config.yml
      - bungeecord:/server

volumes:
  bungeecord: {}
