version: '3.5'

services:
  mc:
    image: itzg/minecraft-server
    environment:
      EULA: "TRUE"
      ONLINE_MODE: "FALSE"
  bungeecord:
    image: itzg/bungeecord
    environment:
      BUNGEE_JAR_REVISION: "1"
    ports:
      - 25565:25577
    volumes:
      - ./config.yml:/server/config.yml